fix rpm install error
    Error: Transaction test error:
      file /usr/bin from install of foo conflicts with file from package
      filesystem-3.8-6.el8.x86_64